CREATE TABLE CATEGORIES (
	ID INT PRIMARY KEY IDENTITY,
	TITLE NVARCHAR(40) NOT NULL,
	DESCRIPTION NVARCHAR(250) NOT NULL
	);

CREATE TABLE SALES (
	ID INT PRIMARY KEY IDENTITY,
	DISCOUNT_NAME NVARCHAR(32) NOT NULL,
	AMOUNT INT NOT NULL,
	DISCOUNT_VALID_TO DATETIME NOT NULL
	);

CREATE TABLE BRANDS (
	ID INT PRIMARY KEY IDENTITY,
	BRAND_NAME NVARCHAR(50) NOT NULL,
	BRAND_REGISTRATION_COUNTRY NVARCHAR(50) NOT NULL,
	MANUFACTURER_COUNTRY NVARCHAR(50) NOT NULL
	);

CREATE TABLE PRODUCTS (
	ID INT PRIMARY KEY IDENTITY,
	SALE_ID INT REFERENCES SALES(ID),
	CATEGORY_ID INT REFERENCES CATEGORIES(ID) NOT NULL,
	BRAND_ID INT REFERENCES BRANDS(ID) NOT NULL,
	PRODUCT_NAME NVARCHAR(64) NOT NULL,
	PRODUCT_DESCRIPTION NVARCHAR(200) NOT NULL,
	RELEASE_DATE DATETIME NOT NULL,
	QUANTITY INT NOT NULL,
	PRICE MONEY NOT NULL,
	IMAGE NVARCHAR(MAX) NOT NULL
	);

CREATE TABLE CLIENTS (
	ID INT PRIMARY KEY IDENTITY,
	NAME NVARCHAR(40) NOT NULL,
	SURNAME NVARCHAR(40) NOT NULL,
	EMAIL NVARCHAR(255) NOT NULL,
	ADDRESS NVARCHAR(200) NOT NULL,
	DATE_OF_BIRTH DATETIME NOT NULL,
	PHONE NVARCHAR(16) NOT NULL,
	EXTRA_PHONE NVARCHAR(16)
	);

CREATE TABLE PAYMENTS (
	ID INT PRIMARY KEY IDENTITY,
	PAYMENT_TYPE NVARCHAR(70) NOT NULL
	)

CREATE TABLE SHIP_TYPE (
	ID INT PRIMARY KEY IDENTITY,
	SHIPPING_NAME NVARCHAR(60) NOT NULL,
	PRICE MONEY NOT NULL,
	SHIPPING_COMPANY NVARCHAR(100)
	);

CREATE TABLE ORDERS (
	ID INT PRIMARY KEY IDENTITY,
	CLIENT_ID INT REFERENCES CLIENTS(ID),
	PAYMENT_ID INT REFERENCES PAYMENTS(ID),
	SHIP_TYPE_ID INT REFERENCES PAYMENTS(ID),
	CITY NVARCHAR(100) NOT NULL,
	DELIVERY_DAY DATETIME NOT NULL,
	QUANTITY INT NOT NULL,
	TOTAL_PRICE MONEY NOT NULL,
	ADDRESS NVARCHAR(150) NOT NULL,
	IS_COMPLETED BIT NOT NULL
	);

	ALTER TABLE ORDERS 
	ADD FOREIGN KEY(SHIP_TYPE_ID) REFERENCES SHIP_TYPE(ID)

CREATE TABLE ORDER_PRODUCTS (
	ID INT PRIMARY KEY IDENTITY,
	ORDER_ID INT REFERENCES ORDERS(ID),
	PRODUCT_ID INT REFERENCES PRODUCTS(ID),
	PRODUCT_QUANTITY INT NOT NULL,
	PRICE MONEY NOT NULL
	);

CREATE TABLE WISH_PRODUCTS (
	ID INT PRIMARY KEY IDENTITY,
	PRODUCT_ID INT REFERENCES PRODUCTS(ID) NOT NULL,
	CLIENT_ID INT REFERENCES CLIENTS(ID) NOT NULL,
	IS_ACTIVE BIT NOT NULL
	);

	USE Citrus

ALTER TABLE SHIPPING_ADDRESSES
ADD STREET NVARCHAR(25)